#!/bin/sh

DW="/var/www/html"                               	# path to installation
DWP="${DW}/data/pages"                    	# path to pages
DWT="${DWP}/admin/template_linked/"     # path to template
SCRIPT="/home/$USER/bin/wikimkdir"
INCRONOPT='IN_ALL_EVENTS '"$SCRIPT"' $$ $@ $# $%'
INCRONTAB="/var/spool/incron/$USER"
LOGFILE="/home/$USER/logfile"
DIRS=`find "$DWP" -type d | grep -w -v "$DWT"`

for DIR in $DIRS
do
## Write entry into incrontab ##
echo -n "${DIR}/ " >> "$INCRONTAB"
echo "$INCRONOPT" >> "$INCRONTAB"
echo '$ added   '"$DIR" >> "$LOGFILE"
done


