#!/bin/sh
# The created incrontab must be moved and the owner changed to the user who then runs the scripts. Can i do that in the script? probably with sudo

DW="/var/www/html"                               	# path to installation
DWP="${DW}/data/pages"                    	# path to pages
DWT="${DWP}/wiki/template_linked/"     # path to template
SCRIPT="/home/$USER/bin/linkedpages/wikimkdir"
INCRONOPT='IN_ALL_EVENTS '"$SCRIPT"' $$ $@ $# $%'
INCRONTAB="/var/spool/incron/$USER"
LOGFILE="/home/$USER/logfile"

IGNORE="${DWP}/wiki/template"

DIRS=`find "$DWP" -type d`

for LINE in $IGNORE
do
DIRS=`echo "$DIRS" | grep -w -v "$LINE"`
done

for DIR in $DIRS
do
## Write entry into incrontab ##
echo -n "${DIR} " >> "$INCRONTAB"
echo "$INCRONOPT" >> "$INCRONTAB"
echo '$ added   '"$DIR" >> "$LOGFILE"
done


